spring.application.name=enterprise-employee-management

spring.datasource.url=jdbc:mysql://localhost:3306/enterprise_employee_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false

server.port=8080

app.security.username=${APP_SECURITY_USERNAME}
app.security.password=${APP_SECURITY_PASSWORD}